-- Create the Masquerade Protocol Database Schema

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'MasqueradeProtocol')
BEGIN
    CREATE DATABASE MasqueradeProtocol;
END
GO

USE MasqueradeProtocol;
GO

-- 1. Worlds: Different game scenarios (Zork, PlanetFall, etc.)
CREATE TABLE Worlds (
    WorldID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    CreatedAt DATETIME DEFAULT GETDATE()
);

-- 2. Rooms: Definitions and base descriptions
CREATE TABLE Rooms (
    RoomID INT PRIMARY KEY IDENTITY(1,1),
    WorldID INT FOREIGN KEY REFERENCES Worlds(WorldID),
    InternalName NVARCHAR(100) NOT NULL,
    DisplayName NVARCHAR(100) NOT NULL,
    BaseDescription NVARCHAR(MAX) NOT NULL,
    IsDark BIT DEFAULT 0
);

-- 3. Exits: Links between rooms
CREATE TABLE Exits (
    ExitID INT PRIMARY KEY IDENTITY(1,1),
    SourceRoomID INT FOREIGN KEY REFERENCES Rooms(RoomID),
    DestRoomID INT FOREIGN KEY REFERENCES Rooms(RoomID),
    Direction NVARCHAR(20) NOT NULL, -- North, South, East, West, Up, Down, etc.
    Description NVARCHAR(MAX) -- Message when moving through
);

-- 4. Characters: NPC and Player character definitions
CREATE TABLE Characters (
    CharacterID INT PRIMARY KEY IDENTITY(1,1),
    WorldID INT FOREIGN KEY REFERENCES Worlds(WorldID),
    Name NVARCHAR(100) NOT NULL,
    SecretGoal NVARCHAR(MAX),
    PersonaPrompt NVARCHAR(MAX),
    IsAlive BIT DEFAULT 1,
    CurrentRoomID INT FOREIGN KEY REFERENCES Rooms(RoomID),
    IsAI BIT DEFAULT 1, -- Defaults to AI for the Understudy system
    Tier INT DEFAULT 1 -- 1: Main, 2: Key NPC, 3: Extra
);

-- 5. Players: User accounts/metadata
CREATE TABLE Players (
    PlayerID INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(100) NOT NULL UNIQUE,
    SessionCookie NVARCHAR(255) UNIQUE,
    LastSeen DATETIME DEFAULT GETDATE()
);

-- 6. Sessions: Active game instances
CREATE TABLE Sessions (
    SessionID INT PRIMARY KEY IDENTITY(1,1),
    WorldID INT FOREIGN KEY REFERENCES Worlds(WorldID),
    StartTime DATETIME DEFAULT GETDATE(),
    EndTime DATETIME,
    IsActive BIT DEFAULT 1
);

-- 7. SessionPlayers: Link between players and their characters in a session
CREATE TABLE SessionPlayers (
    SessionID INT FOREIGN KEY REFERENCES Sessions(SessionID),
    PlayerID INT FOREIGN KEY REFERENCES Players(PlayerID),
    CharacterID INT FOREIGN KEY REFERENCES Characters(CharacterID),
    PRIMARY KEY (SessionID, PlayerID)
);

-- 8. Items: Objects in the world
CREATE TABLE Items (
    ItemID INT PRIMARY KEY IDENTITY(1,1),
    WorldID INT FOREIGN KEY REFERENCES Worlds(WorldID),
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    IsCritical BIT DEFAULT 0,
    IsHidden BIT DEFAULT 0,
    InitialRoomID INT FOREIGN KEY REFERENCES Rooms(RoomID),
    CurrentRoomID INT FOREIGN KEY REFERENCES Rooms(RoomID),
    OwnerCharacterID INT FOREIGN KEY REFERENCES Characters(CharacterID),
    IsUsable BIT DEFAULT 1
);

-- 9. ObjectLinks: Triggers and Signal Bus (Switches, Radios)
CREATE TABLE ObjectLinks (
    LinkID INT PRIMARY KEY IDENTITY(1,1),
    SourceItemID INT FOREIGN KEY REFERENCES Items(ItemID),
    TriggerEvent NVARCHAR(50) NOT NULL, -- TOGGLE, USE, PUSH
    TargetItemID INT FOREIGN KEY REFERENCES Items(ItemID),
    TargetAction NVARCHAR(50) NOT NULL -- SET_STATE_ON, ACTIVATE
);

-- 10. EventLogs: Historical record of all actions
CREATE TABLE EventLogs (
    LogID BIGINT PRIMARY KEY IDENTITY(1,1),
    SessionID INT FOREIGN KEY REFERENCES Sessions(SessionID),
    ActorID INT FOREIGN KEY REFERENCES Characters(CharacterID),
    ActionType NVARCHAR(50) NOT NULL, -- MOVE, SAY, TAKE, USE
    TargetID INT, -- RoomID, ItemID, or CharacterID
    Payload NVARCHAR(MAX), -- The actual text or command
    IsLie BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE()
);

-- 11. WorldFacts: Dynamic lore generated by LLM improvisation
CREATE TABLE WorldFacts (
    FactID INT PRIMARY KEY IDENTITY(1,1),
    SessionID INT FOREIGN KEY REFERENCES Sessions(SessionID),
    EntityID INT, -- RoomID or ItemID
    Attribute NVARCHAR(50) NOT NULL, -- Color, Smell, Texture
    Value NVARCHAR(MAX) NOT NULL,
    FactVector VECTOR(1536), -- SQL 2025 Vector support
    CreatedAt DATETIME DEFAULT GETDATE()
);

-- 12. EntityMetadata: Key-value store for scenario-specific data (Plug-ins)
CREATE TABLE EntityMetadata (
    MetadataID INT PRIMARY KEY IDENTITY(1,1),
    WorldID INT FOREIGN KEY REFERENCES Worlds(WorldID),
    EntityType NVARCHAR(50) NOT NULL, -- 'ROOM', 'ITEM', 'CHARACTER'
    EntityID INT NOT NULL,
    KeyName NVARCHAR(50) NOT NULL,
    KeyValue NVARCHAR(MAX) NOT NULL
);

-- 13. SystemConfig: Global settings, API keys, and model preferences
CREATE TABLE SystemConfig (
    ConfigID INT PRIMARY KEY IDENTITY(1,1),
    Category NVARCHAR(50) NOT NULL, -- 'AI_MODELS', 'NETWORK', 'AUTH'
    ConfigKey NVARCHAR(100) NOT NULL UNIQUE,
    ConfigValue NVARCHAR(MAX) NOT NULL,
    IsSecret BIT DEFAULT 0, -- Mask in UI
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO
